export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const SHOW_EXTRA = "SHOW_EXTRA";
export const HIDE_EXTRA = "HIDE_EXTRA";
export const GET_DATA_START = "GET_DATA_START";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_SINGLE_DATA_START = "GET_SINGLE_DATA_START";
export const GET_SINGLE_DATA_SUCCESS = "GET_SINGLE_DATA_SUCCESS";
